### ISSUE TITLE
Account data structure should include linkStatus or lastImportDate

### ISSUE THREAD

**Issue by Trial-In-Error** [ynab/ynab-sdk-js#109]
Hey! Since the cut-over to Plaid, I've had almost incurable issues with account linking breaking. I've got ~25 linked accounts, and it seems that one or two breaks every week.

I'd like to be able to build some notification / automation layers over this so I can know that an account is no longer correctly linked, but this would require extending the API to either expose a lastImportDate or a linkStatus.

**Comment by bradymholt** [comment]
Thanks for the suggestion!  This does seem like a good addition.  I have a new `direct_import_connected` field in the pipeline to be added which, when true will indicate a successful linked connection.  If false, it will mean the account is not linked or the link is in an unhealthy state.  I can't provide a timeline for getting this released but wanted to let you know this is in the pipeline.
