### ISSUE TITLE
category_id does not accept null value

### ISSUE THREAD

**Issue by mistersender** [ynab/ynab-sdk-js#112]
I am working on  a little CLI for grabbing all of my many amazon orders and getting them to auto-match to the correct line items in ynab to allow me to more quickly and easily figure out the correct categories. In order to do this, I need to be able to get a list of transactions without a category. I tried sending in the id for the "uncategorized" category in the master section, but it yielded no results, so i looked up a transaction i knew had no category and saw that it's category_id was null. Currently, however, the `getTransactionsByCategory` call requires I send in a truthy value, which means that I am not able to search for a category of `null`. I know I could get around this currently by simply getting all transactions, and filtering by categories of null, but it does seem like something that should be fixed properly, assuming this was not an intentional decision. Thanks!

**Comment by bradymholt** [comment]
Thanks for the issue Jessica!  I like the project idea!  My budget has so many Amazon transactions and categorizing takes awhile so I can definitely see the usefulness of doing this. 😄 

The [getTransactions](https://api.youneedabudget.com/v1#/Transactions/getTransactions) endpoint supports a `type` parameter, which can be used to retrieve uncategorized transactions.  Unfortunately, the interface for using `type` in this JavaScript client is a bit awkward and requires passing `undefined` for the `since_date` parameter.

The following should work for retrieving all uncategorized transactions.

```
transactions.getTransactions(budgetId, undefined, "uncategorized")
```

I have opened https://github.com/ynab/ynab-sdk-js/pull/113, which will improve this as follows:

```
transactions.getTransactionsByType("last-used", "uncategorized")
```

Hope this helps!
