### ISSUE TITLE
Updating an uncategorized transaction results in it being force-categorized

### ISSUE THREAD

**Issue by mistersender** [ynab/ynab-sdk-js#114]
Hello again!  Still working on the amazon slurping, but forgot to log this issue (maybe it's a feature??) I encountered while testing. My goal was to be able to have an uncategorized transaction in YNAB match correctly to an amazon order, and then be able to add a memo ONLY to the YNAB transaction via the SDK. (the purpose, then is so i can go into YNAB's uncategorized tab, look at the memo, and be able to quickly update the category in there, as a phase 1).  I'm aware this is almost certainly not an issue with the JS SDK, but I'm not sure where else to log it.

The issue is, whenever I updated the transaction with just the memo, it would fill in the category/categori_id for me, even though i did not send one in. I have to assume this is maybe an issue with CQRS (guessing that is being used on the platform) but it is a kind of surprising behavior that is unwanted. 

### Here are repro steps:

1. Choose an _existing_ transaction that has been categorized. 
2. remove it's category and observe it is now in "uncategorized".
3. use the sdk to add a memo to the transaction. (note: this behavior is observed if i send the entire transaction identical except the memo like a PUT, or if i just send in the memo field like a PATCH.)
4. observe that the transaction has had the memo correctly set, but the transaction has also been re-categorized back into it's previous category.

### Another couple notes: 
* it does seem to revert back to whatever the category it was in before it was marked as "uncategorized" was, which is why i was thinking it may be a CQRS thing. I was able to get around this issue by setting the category_id to the `uncategorized` category id, but this is not very intuitive or expected. 
* I did not try this with a new transaction that never had a category at all, i'm not sure how it would behave in that scenario

**Comment by bradymholt** [comment]
Are you sure you are fetching the transaction in the SDK after it has been uncategorized?  You might try adding `console.log(JSON.stringify(transaction))` on the transaction before sending the memo update to ensure a category_id is not being specified.

I ran a test with the following code and it behaved as I expected - the transaction remained uncategorized after I updated the memo:

```
  // Fetch the transaction before updating the memo
  const transactionResponse = await ynabAPI.transactions.getTransactionById(budgetId, transactionId);
  const transaction = transactionResponse.data.transaction;
  assert.equal(transaction.category_id, null);

  // Update the memo
  const updatedMemo = "Updated memo";
  transaction.memo =updatedMemo;
  await ynabAPI.transactions.updateTransaction(budgetId, transactionId, { transaction });

  // Refetch the transaction and ensure it remains uncategorized
  const transactionRefetchResponse = await ynabAPI.transactions.getTransactionById(budgetId, transactionId);
  const transactionRefetched = transactionRefetchResponse.data.transaction;
  assert.equal(transactionRefetched.category_id, null);
  assert.equal(transactionRefetched.memo, updatedMemo);
```

**Comment by mistersender** [comment]
I will retest it, but will have to be tonight. When I was testing, I was using the get all transactions to get a full list, then grabbing the specific transaction id from that, along with simply looking at the ynab UI. The get all was receiving an uncategorized transaction, and after the update, the ui and get all both updated to have the category. Again though, we were only testing with a transaction that already had a category and i removed it. Not sure this test captures that?

**Comment by bradymholt** [comment]
Was the category removed via the UI the API?

**Comment by mistersender** [comment]
I removed the category in the ui, then confirmed via the get all in the API before updating the memo

**Comment by bradymholt** [comment]
Ok - yeah, I tried that as well when testing and it was retaining `category_id: null`.  `console.log(JSON.stringify(transaction))`  might help to see what it's sending up.

**Comment by mistersender** [comment]
all right, sorry it took me some extra time- those full time jobs + home schooling kids gets in the way of these side projects all the time i'm afraid ;) . I retested using the exact code you posted, but instead of asserts, I added file writes so i could have a record of what i got, what i modified, and what it returned. I am still seeing the exact behavior i described, though :(

**Comment by mistersender** [comment]
as a note, i am happy to provide the actual IDs I used to test this, just maybe not publicly

**Comment by bradymholt** [comment]
@mistersender - sure, if you can send an email to help@ynab.com (be sure to mention me) with those IDs I can try to track down what is going on.  Thanks!

**Comment by mistersender** [comment]
@bradymholt I emailed you pertinent details and a screen recording as well, thanks so much for looking in to this!
