### ISSUE TITLE
Include Rate-Limit Response Header 

### ISSUE THREAD

**Issue by camac** [ynab/ynab-sdk-js#115]
Thanks for this SDK it is working well, just wondering about a nice-to-have.

The API limits to 200 requests per hour, and includes the X-Rate-Limit header in response headers so that you can keep track of your current usage.

Is there any way to access this Rate-Limit header in the response objects?

For example:

```
ynabapi.transactions.updateTransactions(budget.id,{
    transactions: transactionsToUpdate
}).then(res => {
    //Access the response headers here or specifically the current rate limit value
});
```

alternatively is there a way to install a listener for every request so this could be tracked on every request?

**Comment by bradymholt** [comment]
Hi @camac 👋 .

Good idea!  This has been implemented in https://github.com/ynab/ynab-sdk-js/pull/116 and released in version 1.25.0 on npm.

**Comment by camac** [comment]
Thanks very much Brady! I will give this a try tonight after work

**Comment by camac** [comment]
Hi Brady, I have given it a go and unfortunately I am getting null for the rateLimit property of the response object.

this is the output from logging the response object;
![image](https://user-images.githubusercontent.com/663330/118128320-13e9e600-b43e-11eb-91b8-2f9bdc6bf344.png)

I can confirm the header is there in the actual response
![image](https://user-images.githubusercontent.com/663330/118128647-84910280-b43e-11eb-9472-3068c5b5dd39.png)

My best guess is that it could be due the Fetch API respecting some CORS restrictions regarding which headers it is allowed to expose to scripts running in the browser.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

here is a stackoverflow question with a similar problem 

looking at the response from the server, it does include this Access-Control-Expose-Header but it is empty
![image](https://user-images.githubusercontent.com/663330/118129027-02eda480-b43f-11eb-8fca-e218d2f878e7.png)

I am guessing it is beyond the scope of this SDK to modify the YNAB api response headers, but maybe if the response headers included:

    Access-Control-Expose-Headers: X-Rate-Limit

then the fetch api would expose the X-Rate-Limit header through the headers.get method

**Comment by camac** [comment]
also just for additional info I tried in both:
Chrome Version 90.0.4430.212 (Official Build) (64-bit)
Firefox 88.0.1 (64-bit)

**Comment by bradymholt** [comment]
Interesting!  Thanks for the research there.  I did not know only certain response headers were accessible without explicitly exposing them with `Access-Control-Expose-Headers`.  I can make a change on our server for that.  I'll post back once it's released.

**Comment by camac** [comment]
Thanks Brady yeah I didn’t know that either! I just assumed that if you received the headers then you would be able to access them. 
From reading the stackoverflow comments it seem like it was possible if using the old XMLHttpRequest, but the new Fetch API is different.
Great to hear you have access to modify the server response headers, I look forward to giving it a go!

**Comment by bradymholt** [comment]
@camac - A CORS change on the API should go out next Tuesday.

**Comment by camac** [comment]
thanks Brady looking forward to testing it out

**Comment by camac** [comment]
Hey @bradymholt just wanted to let you know I tested at my end and the rateLimit header is now working great. Thanks for your help, I can now display the 'remaining requests' in the user interface 👍

**Comment by bradymholt** [comment]
@camac great!
