### ISSUE TITLE
Unsupported engine

### ISSUE THREAD

**Issue by knifesk** [ynab/ynab-sdk-js#119]
Heya! I'm trying to use the lib but when I try to include the lib I get an error about the engine.

```
Unsupported engine {
npm WARN EBADENGINE   package: 'ynab@1.25.0',
npm WARN EBADENGINE   required: { npm: '^5.2.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.1.3' }
npm WARN EBADENGINE }
```

I'm not a node/JS dev but I'm trying to use the lib in node-red (which uses node). Do you have a clue if making a fork and updating the engine would fix the issue? I have absolutely no idea what's different from 5.2 to 8.1 so I can't really tell if it's not going to work

Ty!

**Comment by bradymholt** [comment]
@knifesk - Hello 👋 .  Ah, that config is a bit outdated.  I just pushed up a [new version](https://www.npmjs.com/package/ynab/v/1.27.0) that should remove that warning.

**Comment by knifesk** [comment]
that's awesome Brady! Thanks!
