### ISSUE TITLE
Empty Payees

### ISSUE THREAD

**Issue by fazulk** [ynab/ynab-sdk-js#130]
Not sure if this is even API related, let alone the JS SDK, but I invoke `transactions.importTransactions` daily, and most of the time it works as expected. But sometimes the Payee will show up blank inside ynab. I can still see the bank import details though.  It usually only happens maybe 2 or 3 days out of the month. Wish I could replicate it somehow. Any direction would be great.

**Comment by bradymholt** [comment]
Hi Jeff 👋  - This can best be handled by sending an email to our Support Team (help@youneedabudget.com).  They should be able to troubleshoot this for you!
