### ISSUE TITLE
`getTransactionsByCategory` does not include `server_knowledge` in type

### ISSUE THREAD

**Issue by dotNomad** [ynab/ynab-sdk-js#145]
While working on a script for my YNAB budget I noticed that the `api.transactions.getTransactionsByCategory` return type does not include `"server_knowledge"`.

Other methods like `api.transactions.getTransactions` do and it seems like the endpoint response [`/budgets/{budget_id}/categories/{category_id}/transactions`](https://api.youneedabudget.com/v1#/operations/Transactions/getTransactionsByCategory) does contain that key since it supports the `last_knowledge_of_server` parameter.

**Comment by bradymholt** [comment]
Thanks! This should be fixed in [1.42.0](https://www.npmjs.com/package/ynab/v/1.42.0).
