### ISSUE TITLE
PATCH transactions does not work for subtransactions

### ISSUE THREAD

**Issue by dotNomad** [ynab/ynab-sdk-js#149]
Using [the update transactions API endpoint](https://api.youneedabudget.com/v1#/Transactions/updateTransactions) I noticed it does not work for subtransactions the way I expected.

### With a subtransaction ID

If I provide data like:
```
{
  "transactions": [
    {
      "id": "<SUBTRANSACTION_ID>",
      "memo": "3.0"
    }
  ]
}
```

I get a response like:

```
{
  "error": {
    "id": "400",
    "name": "bad_request",
    "detail": "transaction does not exist in this budget (index: 0)"
  }
}
```

Which leads me to believe that this endpoint only supports `ynab.TransactionDetail` type transactions, and not subtransactions via the ID. This was a bit counter intuitive since subtransactions are still transactions that have an ID.

### With subtransactions key

If I provide data like:
```
{
  "transactions": [
    {
      "id": "<PARENT_TRANSACTION_ID>",
      "subtransactions": [{
        "id": "<SUBTRANSACTION_ID>",
        "memo": "3.0"
      }]
    }
  ]
}
```

I get a response like:

```
{
  "error": {
    "id": "400",
    "name": "bad_request",
    "detail": "amount must equal the sum of subtransaction amounts (index: 0)"
  }
}
```

Which leads me to believe that I must provide all subtransactions instead of only patching the details I would like. This makes sense because here I am PATCHing the entire `subtransactions` array.

---

Is the only way to update a subtransaction to have the entire parent's subtransaction data and use that to PATCH the `subtransaction` array?

This is pretty limiting for my use case where I'm attempting to sync two budgets that are using the ["Splitwise in your Register" method](https://support.youneedabudget.com/en_us/splitwise-and-ynab-a-guide-H1GwOyuCq#register).

I currently am saving previously synced transactions to a database, and am attempting to keep those settled transactions synced if a memo or amount is updated. I was theorizing that I could do this by storing the two transaction IDs, but since one is a subtransaction it seems that I will have to store a lot more data to PATCH it. Unless I am missing a method in the API or the API is not working as intended with subtransactions.

**Comment by bradymholt** [comment]
Unfortunately, the API does not support what you are trying to do.

> Which leads me to believe that this endpoint only supports ynab.TransactionDetail type transactions, and not subtransactions via the ID

That is correct.  Subtransactions are logically different entities in the API and we only support a PATCH on _transactions_, not _subtransactions_.

> Which leads me to believe that I must provide all subtransactions instead of only patching the details I would like

That is correct.  When patching a transaction with subtractions, you must provide all the subtraction data, as the transaction patch does not require patching individual subtransactions.

Hope this helps!

**Comment by dotNomad** [comment]
> Unfortunately, the API does not support what you are trying to do.

Ah, bummer! Is there a good spot for me to submit a feature request (if YNAB has that in a public spot)?

> Hope this helps!

The clarification definitely helps. I'll have to scrap some of the ideas I had with my tool, but that is alright.

**Comment by bradymholt** [comment]
Yes - you can submit a feature request through help@ynab.com.
