### ISSUE TITLE
Question: Best way to get subtransactions of a given transactions?

### ISSUE THREAD

**Issue by sandrina-p** [ynab/ynab-sdk-js#153]
Hi team!

I'm using your API to build some custom reports and I realized that when a transaction has multiple categories, the "split" info is not included in the transaction itself, but rather in `myData.subtransactions`.

My question is: What's the best way to know that a given transaction is split into multiple categories and get its `subtransactions`?

Currently, I'm doing like this:

```js
const myData = await ynabAPI.budgets.getBudgetById(myPersonalId)

const myTransactionId = '12345' // an arbitrary transaction

const isMyTransactionSplitted = myData.subtransactions.filter(t = t.transaction_id === myTransactionId).length > 0
```

It works, but from a performance perspective, this means that I'd need to always loop through all `myData.subtransactions` to know if it is splitter or not. 

Is there a better way of doing this?

**Comment by bradymholt** [comment]
Hi @sandrina-p 👋 .  If a transaction is split, it should have a special _category_ indicating it is a split.  For details and further help, could you please email your question to our support team at help@ynab.com?  They should be able to help you out!

**Comment by sandrina-p** [comment]
What's that "special category" name? I noticed it has a unique `id`, but it's not listed in the `myData.categories`. What am I missing here?

**Comment by sandrina-p** [comment]
Hi again @bradymholt, I came back to this pet project, and I must report that the category "Split (Multiple Categories)" does not exist under `budget.data.categories`. So any transaction that is split, I can't identify it in any way besides hardcoding that specific `category_id` :/ 

Can you please confirm?

**Comment by bradymholt** [comment]
The `category_name` on the parent transaction should be "Split".  I was mistaken with my response earlier.  Here is an example of a transaction response record that is a split.

```
{
        "id": "f88fff92...",
        "date": "2024-02-12",
        "amount": -10000,
        "memo": null,
        "cleared": "uncleared",
        "approved": true,
        "flag_color": null,
        "account_id": "d7e3ed3b...",
        "account_name": "Checking",
        "payee_id": null,
        "payee_name": null,
        "category_id": "90e94f8f...",
        "category_name": "Split",
        "transfer_account_id": null,
        "transfer_transaction_id": null,
        "matched_transaction_id": null,
        "import_id": null,
        "import_payee_name": null,
        "import_payee_name_original": null,
        "debt_transaction_type": null,
        "deleted": false,
        "subtransactions": [
          {
            "id": "a17fa878...",
            "transaction_id": "f88fff92...",
            "amount": -5000,
            "memo": null,
            "payee_id": null,
            "payee_name": null,
            "category_id": "6c3e803d...",
            "category_name": "Rent/Mortgage",
            "transfer_account_id": null,
            "transfer_transaction_id": null,
            "deleted": false
          },
          {
            "id": "4cba78ad...",
            "transaction_id": "f88fff92...",
            "amount": -5000,
            "memo": null,
            "payee_id": null,
            "payee_name": null,
            "category_id": "f7614658...",
            "category_name": "Water",
            "transfer_account_id": null,
            "transfer_transaction_id": null,
            "deleted": false
          }
        ]
      }
```
