### ISSUE TITLE
GETting account balances by month

### ISSUE THREAD

**Issue by marr00n** [ynab/ynab-sdk-js#161]
This may be a very basic problem, but I am struggling to determine how to solve it.

I am wanting to GET historical account balances for the last year. Looking at the endpoints, I don't see this as an option within
 /budgets/{budget_id}/accounts
 /budgets/{budget_id}/months 

My current thought is to get the current account balances, and then deduct account-specific transactions from the balance to determine the balance at a certain point in time. But this just seems like the long way around.

Have I missed an appropriate endpoint in your API?

**Comment by bradymholt** [comment]
The API does not provide historical account balance so your approach of backing our transaction amounts would probably be the best way 👍 .
