### ISSUE TITLE
`null` values in `TransactionDetails` incorrectly showing as invalid

### ISSUE THREAD

**Issue by dotNomad** [ynab/ynab-sdk-js#162]
Noticed a typing inconsistency while working on testing a YNAB script:

When retrieving transactions from the endpoint `GET /budgets/{budget_id}/transactions` the transactions received can have:

```
flag_color: null,
debt_transaction_type: null,
```

These show as invalid with the TypeScript types given.

`TransactionDetailFlagColorEnum` has `Null: "null"` which is not equivalent to `null`. The same goes for `TransactionDetailDebtTransactionTypeEnum`.

**Comment by bradymholt** [comment]
Thanks!  This is fixed in https://github.com/ynab/ynab-sdk-js/pull/163.

**Comment by dotNomad** [comment]
Awesome! Thank you for the fix. 🎉
