### ISSUE TITLE
Rate limit values are no longer shown

### ISSUE THREAD

**Issue by SathyaBhat** [ynab/ynab-sdk-js#164]
In #116 the rate limit value was added to the response object. It looks like with the new OpenAPI spec, the rate limit values are either omitted from the header/body and not exposed at all.

**Comment by bradymholt** [comment]
Yes, the `rateLimit` property was removed in v2.0.0 when the library was switched over from Swagger to OpenAPI Generator.  Please see related [release notes](https://github.com/ynab/ynab-sdk-js/releases/tag/v2.0.0).

**Comment by SathyaBhat** [comment]
@bradymholt THanks, I missed that. Any suggestions on how to keep track of the rate limit now that the response object doesn't have it?
