### ISSUE TITLE
Wrong Method-Name in Readme

### ISSUE THREAD

**Issue by Nepomacs** [ynab/ynab-sdk-js#172]
Hi YNABers,

i noticed a small error in the Readme.

The Method `months.getMonthCategory_by_id(budget_id, month, category_id)` does not exist.

Instead the right one seems to be`categories.getMonthCategoryById(budget_id, month, category_id)`.

I've created a PR to fix documentation (#171)

Greetings :-)

**Comment by bradymholt** [comment]
Fixed by https://github.com/ynab/ynab-sdk-js/pull/171
