### ISSUE TITLE
Any way to delete/modify subtransactions?

### ISSUE THREAD

**Issue by justinhaaheim** [ynab/ynab-sdk-js#174]
Hey team - I saw in the docs that modifying subtransactions isn’t supported right now by the API. I see that I can create them through an updateTransactions api call. Is there a way to remove them? Could I call deleteTransaction on the subtransaction ID to accomplish that?

It seems to me like there would need to be a way to delete all the subtransactions at once in order to avoid situations where the subtransactions don’t add up to the total.

**Comment by bradymholt** [comment]
Hi @justinhaaheim - deleting subtransactions directly is not currently supported.  You can call `DELETE` [on the parent transaction](https://api.ynab.com/v1#/Transactions/deleteTransaction) which would also delete all the subtransactions for that parent, but you cannot delete individual subtransactions.  Feel free to reach out to help@ynab.com to let us know if you'd like this feature!
