### ISSUE TITLE
CORS Error when deleting a transaction

### ISSUE THREAD

**Issue by justinhaaheim** [ynab/ynab-sdk-js#178]
Hi folks,
I have a web app that uses this sdk to "label" transactions in YNAB using information from Amazon/Target (it reconciles amazon/target orders to individual transactions so you know how a transaction should be categorized).

Everything was working perfectly until this evening when I added some code that calls `ynabAPI.transactions.deleteTransaction()`. (Fwiw I'm doing this as a workaround for not being able to delete/modify subtransactions using the current API. The workaround is to delete the transaction and then create a new one with most of the same properties, minus the subtransactions array)

Calling deleteTransaction throws a CORS-related error in the console:

```
Access to fetch at 'https://api.ynab.com/v1/budgets/[budget-id-redacted]/transactions/[transaction-id-redacted]' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It looks like the response headers to the OPTIONS preflight request the browser makes don't contain the normal CORS headers:

```
cf-cache-status:
DYNAMIC
cf-ray:
8dd407dfb8a0270a-SJC
content-length:
0
date:
Mon, 04 Nov 2024 10:48:16 GMT
nel:
{"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
report-to:
{"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1730717296&sid=af571f24-03ee-46d1-9f90-ab9030c2c74c&s=vaWg09IBRj50oBAS8U6peU7KqGCFvkKuRA3lpMDLpUM%3D"}]}
reporting-endpoints:
heroku-nel=https://nel.heroku.com/reports?ts=1730717296&sid=af571f24-03ee-46d1-9f90-ab9030c2c74c&s=vaWg09IBRj50oBAS8U6peU7KqGCFvkKuRA3lpMDLpUM%3D
server:
cloudflare
server-timing:
cfL4;desc="?proto=TCP&rtt=6794&sent=102&recv=69&lost=0&retrans=0&sent_bytes=40125&recv_bytes=5863&delivery_rate=3804838&cwnd=256&unsent_bytes=0&cid=34e0b61340fd22fd&ts=372927&x=0"
strict-transport-security:
max-age=63072000; includeSubDomains
via:
1.1 vegur
```

The preflight OPTIONS requests for the updateTransactions calls *do* have the following headers:

```
access-control-allow-headers:
authorization,content-type
access-control-allow-methods:
GET, POST, PUT, PATCH, OPTIONS
access-control-allow-origin:
*
access-control-expose-headers:
X-Rate-Limit
access-control-max-age:
7200
...
```

Seems like there may be an issue with the CORS configuration for DELETE requests? Or maybe I'm missing something?

**Comment by leslie-heinzen** [comment]
Thanks for the report @justinhaaheim. Your hunch is correct about the CORS configuration. It looks like calling this endpoint from a browser has been an issue for some time.

@bradymholt here's a stripped-down repro: https://github.com/leslie-heinzen/ynab-js-sdk-178-delete-txn-cors-err-repro

We'll update when there's a decision/fix.

**Comment by bradymholt** [comment]
Thanks @justinhaaheim and @leslie-heinzen.  It does look like we're missing `DELETE` method in our server config.

**Comment by leslie-heinzen** [comment]
@justinhaaheim The fix for this should be deployed after Wednesday, and won't require any changes on your end. Thanks again for reporting the issue.

**Comment by justinhaaheim** [comment]
Thanks for the quick response @leslie-heinzen and @bradymholt!
