### ISSUE TITLE
npm published code out of sync with documentation

### ISSUE THREAD

**Issue by ctlevi** [ynab/ynab-sdk-js#43]
Super minor, but I had to look at the compiled JS in node_modules to figure this one out. The current README uses `new ynab.API()`, but the current code in npm does not have that available yet, instead it only seems to have `new ynab.api()`. I probably should have went to npm's README, but I usually just look at the github page, so it threw me off.

Furthermore, the [api documentation page](https://api.youneedabudget.com/#client-javascript) seems to be using an even older initialization that is no longer available and gives you `TypeError: ynabApi is not a constructor`

**Comment by bradymholt** [comment]
Thanks @ctlevi !  [v 0.16.0](https://www.npmjs.com/package/ynab/v/0.16.0) on npm has been published which should include the updated interface.  We'll get the docs updated as well.  We made this change but hadn't pushed it up to npm yet but as you pointed out the README was out of sync with what was published.  Thanks for pointing that out!

**Comment by bradymholt** [comment]
@JulianKingman You are correct - the README had wrong method name formats.  I've fixed here:https://github.com/ynab/ynab-sdk-js/pull/59 and made a few other improvements [released as 1.5.0 on npm](https://www.npmjs.com/package/ynab).
