### ISSUE TITLE
Publish precompiled code to npm?

### ISSUE THREAD

**Issue by tomcheng** [ynab/ynab-sdk-js#47]
I'm using this library in project built with create-react-app, and the build step is giving this error:

```
Failed to minify the code from this file:

 	./node_modules/ynab/dist/esm/index.js:10

Read more here: http://bit.ly/2tRViJ9
```

The link resolves to this: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

And to quote that link:

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

Thanks!

**Comment by bradymholt** [comment]
Thanks @tomcheng for reporting the issue and the legwork of finding out what the root cause was!

I've pushed up https://www.npmjs.com/package/ynab/v/0.17.0 which targets ES5 for the browser and ESM builds which should fix the issue for you.

**Comment by tomcheng** [comment]
@bradymholt Great, thanks!
