### ISSUE TITLE
Authorize URL Redirects to YNAB App on Android

### ISSUE THREAD

**Issue by dkisselev** [ynab/ynab-sdk-js#52]
This isn't strictly an issue with the JS SDK, but affects any JS SDK app that uses the authorize endpoint to get access tokens.

Repro:
1. Ensure that the YNAB app is installed on the device
2. Open a third-party YNAB web app in Chrome
3. Click an Authorize link that attempts to go to `https://app.youneedabudget.com/oauth/authorize?client_id=...`
4. Observe that the YNAB app opens to one of the main pages, but can't handle the oauth flow

The deeplink handler in the app may need to be tweaked to exclude oauth URLs so that the flow can be completed within the browser.

**Comment by bradymholt** [comment]
Thank you @dkisselev - I'll check with the Android folks on our team to handle this correctly.

**Comment by bradymholt** [comment]
@dkisselev I've reported this internally and will follow though on it.  Can you check to see if the deeplink still kicks in if you use `api` subdomain for the OAuth flow?  For example, can you try OAuth flow with https://*api**.youneedabudget.com/oauth/authorize?client_id=... URL?

**Comment by bradymholt** [comment]
@dkisselev I've confirmed using the `api` subdomain will _not_ invoke the deeplink on Android.

We'll get the Android app updates to prevent deeplinking on `app` subdomain for OAuth but in the meantime, please use `api` subdomain for the authorization URL like this:

https://API.youneedabudget.com/oauth/authorize?client_id=...

**Comment by dkisselev** [comment]
Thanks Brady, you beat me to it but you're right that the Android app currently only claims app.youneedabudget.com URL's so api would work fine.

Thanks for the quick turnaround!
