### ISSUE TITLE
Provide method to format currency

### ISSUE THREAD

**Issue by alanrussian** [ynab/ynab-sdk-js#58]
It would be helpful if there were a utility to format a currency in the user's configured currency format. Example API:

```
format_currency(CurrencyFormat currencyFormat, int amountMillis) -> String
format_currency(enUsCurrencyFormat, 1234560) -> '1,234.56'
```

**Comment by bradymholt** [comment]
@alanrussian Thanks for the suggestion.  There is [ynab.utils.convertMilliUnitsToCurrencyAmount](https://github.com/ynab/ynab-sdk-js#utilities) which will take milliunits and a currencyDecimalDigits parameter to do most of the work.  Is your suggestion to go a bit further with formatting as it is displayed in YNAB to add the symbol and group separator (comma, period, etc.)?

**Comment by bradymholt** [comment]
To keep the client focused on interaction with the API, we'd prefer to not introduce full currency formatting at this time but we'll keep it in mind for future enhancements.  Thank you, though, for the suggestion.  If you end up doing any work in this area in an OSS project of yours please post back and let us know so others can benefit!
