### ISSUE TITLE
Categories are not properly assigned to created transactions

### ISSUE THREAD

**Issue by ravishi** [ynab/ynab-sdk-js#75]
When I create a bunch of transactions, their categories don't get assigned properly. Only a few of them end up categorized in YNAB.

I'm using the latest version of this SDK, and I've downloaded all my transactions using `getTransactions()`, then I've matched their `category_id`s  with a new set of transactions (I want to update their `import_id`s). When I create them using `createTransactions()` and look at YNAB interface, their categories are not filled.

What's happening here?

**Comment by bradymholt** [comment]
@ravishi - This might be budget specific.  Could you send an email to api@youneedabudget.com with some more specifics and possibly a snippet of the code you are using?  Also, if you are able to reproduce with a single transaction (i.e. calling `createTransactions()` with a single transaction, specifying a category_id that is not getting set, that would be very helpful.
