### ISSUE TITLE
500 (Internal server error) on transaction with hidden whitespace characters

### ISSUE THREAD

**Issue by moranje** [ynab/ynab-sdk-js#76]
Hi!

Not sure if this is an API problem or a problem with the way the js SDK is handeling the request to the API. If nothing else hopefully I'm forwarded to the proper channels.

```js
import * as ynab from 'ynab';
let accessToken = "<removed>";
let budgetId = "<removed>";
let api = new ynab.API(accessToken);

// ...

api.transactions.createTransaction(budgetId, { transactions: payload })

```

With the following payload:

```JSON
[{
	"id": "<removed>",
	"account_id": "<removed>",
	"account_name": "Gezamelijk",
	"date": "2019-03-02",
	"amount": -45870,
	"memo": "Maandpremie maart 2019\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 van verzekering"
}]
```

And it consistently fails with a `500 (Internal server error)` so I'm assuming something in this request breaks the server. My best guess it that it has  to do  something with this exact amount. I've had another transaction with this exact amount fail with the same error.

Any thoughts?

**Comment by bradymholt** [comment]
@moranje - Strange! So, with this example, do you still get the error if you change the amount?

**Comment by moranje** [comment]
Nope, I was being silly. It was due to the crazy unicode whitespace chars in the memo. Still that's not supposed to break the server right?

<img width="1066" alt="Schermafbeelding 2019-03-18 om 21 28 46" src="https://user-images.githubusercontent.com/666528/54561474-0acb6e80-49c5-11e9-8eb8-474f56ce6776.png">

**Comment by bradymholt** [comment]
Thanks - this is a server issue and I will create an internal issue for it.  Thank you!

**Comment by george** [comment]
@moranje Just following up on this. I just merged a PR to better surface this error, instead of sending back an opaque `HTTP 500` response. Now we'll return `HTTP 400` with the following JSON payload:

```json
{
  "error": {
    "id": "400", 
    "name": "bad_request", 
    "detail": "unsupported Unicode escape sequence in request payload (JSON)"
  }
}
```

This will get pushed out to production next Tuesday (3/26), noon-ish EDT. Let me know if you have any questions.

**Comment by moranje** [comment]
Thanks for the update!

Op vr 22 mrt. 2019 22:13 schreef George Anderson <notifications@github.com>:

**Comment by george** [comment]
@moranje I totally messed up: I forgot to merge the PR in time for today's deployment. I apologize. I was waiting for the tests to build green and never circled back to merge. So now this fix will be deployed to production this Thursday, 3/28. Cheers.

**Comment by george** [comment]
@moranje One last update: this fix is now live in production. I just tested it and got a 400 Bad Request response, as expected:

```json
{
    "error": {
        "id": "400",
        "name": "bad_request",
        "detail": "unsupported Unicode escape sequence in request payload (JSON)"
    }
}
```

Thanks for the report and your patience with the fix :)
