### ISSUE TITLE
Cross-Origin Read Blocking

### ISSUE THREAD

**Issue by moranje** [ynab/ynab-sdk-js#78]
```
VM18275:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://api.youneedabudget.com/v1/budgets/<...> with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

This [page](https://www.chromium.org/Home/chromium-security/corb-for-developers) seems to suggest to change the `Content-Type` header but there's no way to set this. It would seem that it's een client responsibility. Would you agree?

**Comment by bradymholt** [comment]
@moranje - We should be sending back `Content-Type: application/json` as a response header.  Are you sure the access token is valid and that the URI is valid?  You might want to give the request a try manually outside of the browser to make sure you are getting a valid response. 

I just ran:

```
curl -sSL -D - -H "Authorization: Bearer <snip>" https://api.youneedabudget.com/v1/budgets/last-used/transactions -o /dev/null
```

And got output that looks like this:

```
HTTP/1.1 200 OK
...
Content-Type: application/json; charset=utf-8
X-Rate-Limit: 8/200
...
```

**Comment by moranje** [comment]
Not sure if it's that then. I've tried adding transactions through Postman, which seems to  work  (no errors)  and I'm getting a list of transactions in the return response. Maybe I'm blocked from adding transactions somehow... Any idea where to get support for these kinds of problems?

**Comment by bradymholt** [comment]
@moranje - Please send an email to api@youneedabudget.com and we'll get you squared away.  I'd recommend including the IP address you are using so we can make sure you aren't being blocked.

**Comment by moranje** [comment]
Thanks for taking the time to respond. The problems disappeared as suddenly as they appeared. I'll be sure to follow your suggestion next time this happens.
